/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const TodosIndexLazyRouteImport = createFileRoute('/todos/')()
const TodosIdLazyRouteImport = createFileRoute('/todos/$id')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TodosIndexLazyRoute = TodosIndexLazyRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/todos/index.lazy').then((d) => d.Route))
const TodosIdLazyRoute = TodosIdLazyRouteImport.update({
  id: '/todos/$id',
  path: '/todos/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/todos/$id.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/todos/$id': typeof TodosIdLazyRoute
  '/todos/': typeof TodosIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/todos/$id': typeof TodosIdLazyRoute
  '/todos': typeof TodosIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/todos/$id': typeof TodosIdLazyRoute
  '/todos/': typeof TodosIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos/$id' | '/todos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos/$id' | '/todos'
  id: '__root__' | '/' | '/todos/$id' | '/todos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TodosIdLazyRoute: typeof TodosIdLazyRoute
  TodosIndexLazyRoute: typeof TodosIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos/'
      preLoaderRoute: typeof TodosIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$id': {
      id: '/todos/$id'
      path: '/todos/$id'
      fullPath: '/todos/$id'
      preLoaderRoute: typeof TodosIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TodosIdLazyRoute: TodosIdLazyRoute,
  TodosIndexLazyRoute: TodosIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
